// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queries.sql

package db

import (
	"context"
)

const getEmails = `-- name: GetEmails :many
SELECT EMAIL FROM REGISTRED_USERS ORDER BY ID ASC
`

func (q *Queries) GetEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
